[mypy]
python_version = 3.12

files = app

exclude = ^tests/

warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True

show_error_codes = True
pretty = True

ignore_missing_imports = True

namespace_packages = True
explicit_package_bases = True
