"""
HAPT Risk Manager
-----------------

Evaluates whether a proposed trade satisfies
HAPT risk management rules.

Position sizing is intentionally handled by the
PositionSizingEngine.
"""

from app.models.decision import Decision
from app.models.risk import Risk


class RiskManager:
    """Evaluates trade risk according to HAPT rules."""

    def __init__(self, max_risk: float = 30.0):
        self.max_risk = max_risk

    def get_max_risk(self) -> float:
        """Return the maximum dollar risk per trade."""
        return self.max_risk

    def evaluate(
        self,
        decision: Decision,
        entry_price: float,
        stop_loss: float,
        target_price: float,
        position_size: float,
    ) -> Risk:
        """
        Evaluate whether a trade satisfies
        HAPT risk management rules.

        Parameters
        ----------
        decision:
            Decision generated by the DecisionEngine.
        entry_price:
            Planned entry price.
        stop_loss:
            Planned stop-loss price.
        target_price:
            Planned target price.
        position_size:
            Position size already calculated by the
            PositionSizingEngine.

        Returns
        -------
        Risk
            Risk evaluation result.
        """

        risk = Risk()

        risk.risk_amount = self.max_risk
        risk.entry_price = entry_price
        risk.stop_loss = stop_loss
        risk.target_price = target_price
        risk.position_size = position_size

        stop_distance = abs(entry_price - stop_loss)
        reward_distance = abs(target_price - entry_price)

        if stop_distance > 0:
            risk.risk_reward = round(
                reward_distance / stop_distance,
                2,
            )

        risk.approved = (
            decision.grade in ("A+", "A")
            and risk.position_size > 0
            and risk.risk_reward >= 2.0
        )

        if risk.approved:
            risk.notes.append(
                "Trade satisfies HAPT risk rules."
            )
        else:
            risk.notes.append(
                "Trade rejected by HAPT risk rules."
            )

        return risk